README.md
all.toml
clippy.toml
dev-tools.toml

As Clippy is a sub-team of dev-tools, this adds 2 new toml files: `dev-tools.toml` and `clippy.toml`. The `dev-tools.toml` file just includes the `clippy.toml` file, as the dev-tools team currently doesn't have a recurring meeting.
---
Question: In my personal calendar I also have reminders for Clippy to do the Rust<->Clippy repo sync, the release, and beta-backports. Can/Shall those reminders also be included in the team calendars?

Add Clippy calendar

---

all.toml

The calendar defined by `all.toml` does not build correctly because it requires two files that do not exist:
- `language.toml`
- `library.toml`
The corresponding files were instead named:
- `lang.toml`
- `libs.toml`
These names are better as they match the conventional names of the teams.  So let's fix the "all" calendar by updating it to refer to these files.

Fix "all" calendar

---

lang.toml

We want the lang team calendar to represent only the meetings of the lang team itself rather than having it also include meetings of its subteams and chartered working groups and initiatives.
Currently, the calendar includes two non-T-lang meetings.  One is for T-opsem and the other is for project-ffi-unwind.  If these meetings were still alive, we would move them to separate calendars.  However, as far as we can tell, at the moment these meetings are not happening at the times and places scheduled here.
Consequently, let's simply remove these obsolete meetings from the lang team calendar, leaving only active T-lang meetings.

Remove obsolete meetings from T-lang calendar

---

README.md
dev-tools.toml
testing-devex.toml

This PR adds a calendar for the Testing DevEx team.
Note: Testing DevEx [does not have an email](https://github.com/rust-lang/team/blob/ae0fe5cb83bbb24c9533c6829f2ca11667e8ab2d/teams/testing-devex.toml), so I went ahead and [used one of `devtools`](https://github.com/rust-lang/team/blob/ae0fe5cb83bbb24c9533c6829f2ca11667e8ab2d/teams/devtools.toml#L42) as it is the parent team of `testing-devex`.
cc @rust-lang/testing-devex

feat: Add testing-devex team calendar

---

lang.toml
wg-async.toml

In many kinds of calendaring software, a person working in an organization will make his or her calendar available to others in such a way that those others can try to schedule around times when that person is busy.  To do this, calendaring software distinguishes between events that make the person busy and those that don't.
In the iCalendar standard, this is termed the "transparency" of the event.[^1]  An event which is "opaque" is one that consumes the attention of that individual.
The tooling here[^2] does not emit any "transparency" property in the output ICS file by default.  If we want this property emitted, we need to specify it.  Without it specified, calendaring software may use whatever its own default is.
The lang team meetings and those of WG-async are fully consuming. Let's …

Mark subscribers as busy during T-lang, WG-async events

---

cargo.toml

`num` really wasn't intended to be used for `cargo` but was required until [`calendar-generation#6`](https://github.com/rust-lang/calendar-generation/pull/6). This PR removes `num` from `1704825224734`.

fix(cargo): Remove `num` from `ByDay`

---

release.toml

Silly mistake in the name.
r? @davidtwco

Fix Rust Releases calendar name

---

README.md
all.toml
wg-binary-size.toml

For now, the timezone is UTC and so won't change with daylight savings. I included a link to the Zulip in the description as well, since putting it in the location makes it unclickable in Google Calendar (it tries to open Maps).
I confirmed it looks right when imported into my calendar.
@Kobzol @saethlin

Add wg-binary-size meetings

---

lang.toml

We decided to extend our design meetings to 90 minutes and to start each half an hour earlier.  To preserve consistency, let's do the same for the planning meetings.  Those often will not need the full 90 minutes on most months, but given the upcoming edition we may in fact need this, and we can of course hand the time back to people.
To implement this, we create two new events and we mark the existing events as having ended.  We do it this way as modifying the existing events would retroactively change the time of the events that have already occurred.
For the new events, we use 160-bit random identifiers to ensure that these are globally-unique as required by IETF RFC 5545.

Extend T-lang design/planning meetings to 90 minutes

---

lang.toml

(Merge this after #39 to prevent conflicts.)
We're meeting 2024-03-04 to discuss the syntax of RTN.  This is a one-off event, so no recurrence rules are specified.

Add one-off T-lang meeting for RTN syntax

---

libs.toml

This keeps meeting times aligned with other Rust teams during US/Europe DST mismatch.

Base libs meetings on US timezone for DST

---

types.toml

I'd like to fix the calendar of the @rust-lang/types.
The current commit just removes "Types Team: Rotating Solver/Formality/Polonius Deep Dive" as is not happening anymore.
I'm not sure about "Types Team: ITE (Impl Trait Everywhere) Triage".
And the "Types Team Meeting" is not happening either but not sure if we want to keep it.
Also ... what timezone should we use for these ones?. US timezone? if so ... can somebody point me to the right timing of the meetings in said timezone?.

Fix Types Team meetings

---

rustdoc.toml

It seems we are de facto using Paris time, so we might as well update
the official timing. Note that European daylight saving almost always
matches American daylight saving, except for March (at least that's the
only exception for the next year).
cc @GuillaumeGomez

Update rustdoc meeting timezone

---

wg-async.toml

The WG-async meetings had been scheduled on UTC time on this calendar.  However, that's probably not what we had intended, so let's fix that.
We'll instead schedule these meetings on U.S. time (and thus follow the schedule for U.S. DST) as that's most common for the project, and in particular, because that's how the Monday T-types and the Thursday T-spec meetings are scheduled, and we don't want to jump around with respect to those.
For the Thursday meeting, however, we'd been discussing moving that back an hour anyway.  The effect of DST pushed it back an hour in March, and we'll keep with that when converting the timezone.  To preserve the correctness of earlier calendar events, we'll retire the old event and create a new one.  In doing this, we'll go ahead and separate out the design …

Update WG-async meetings for time and TZ change, etc.

---

wg-async.toml

We meet on Thursdays for the WG-async design and planning meetings. When updating these events on the calendar recently, we inadvertently moved these to Wednesdays.  Let's fix that.

Fix day of week of WG-async design/planning meetings

---

libs.toml

libs-api: Instead of a bi-weekly 1 hour meeting for processing ACPs, use a weekly 2 hour meeting.
libs: Change meeting length to 30 minutes instead of 1 hour to avoid conflicting with the lang design meeting.

Update libs & libs-api meeting times

---

lang.toml

We have a lang planning meeting scheduled for the first Wednesday of every month.  This was set up as a monthly-recurring event starting on 2024-03-06, which was a Wednesday.
However, what that actually encodes is a meeting every month on the 6th.  That's not what we want and has been confusing people, so let's retroactively end that recurrence.
We don't need any replacement here, as we actually just use our design meeting slot for this, and lately we've been mixing it up a bit and not always doing these on the first Wednesday of the month.
cc @davidtwco

End broken lang planning meeting event

---

README.md
compiler.events-only.toml

As per the [Zulip meeting](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202024-11-08.20Planning.20meeting/near/481333860), here the new scheduled meetings for T-compiler.
I think I can merge this, but leaving it here to allow a quick review.
Thanks!
cc @davidtwco 
EDIT: updated with the suggested swap (see [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202024-11-08.20Planning.20meeting/near/481354131))

Update T-compiler calendar

---

types.toml

Removed the weekly occurrence from two Types team meetings that are not taking place anymore, this should be enough to remove them from our calenders.
(agreed this change with @lcnr )
r? @tgross35 
thanks!

Update Types Team calendar

---

LICENSE-APACHE
LICENSE-MIT
README.md

I may propose we add some small bits of code to this repository to handle generating UIDs, and so that would in particular call for having a license here.
But even aside from that, it's better for all repositories in our project to have a license, so let's agree to distribute this under the terms of `MIT OR Apache-2.0`.
cc @davidtwco

License under `MIT OR Apache-2.0`

---

wg-debugging.toml

As discussed [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/317568-t-compiler.2Fwg-debugging/topic/Calendar.20for.20triage.20meeting.20update).
cc: @davidtwco

Disable wg-debugging triage meeting

---

types.toml

In this commit https://github.com/rust-lang/calendar/commit/4afc4d5fa9ecff59b8711ce1f9baf9ad0f0458ba we did not update last_modified_on

Fix last modified_on for old events that were not updated

---

types.toml

This makes the meeting start the first Tuesday of 2025.
One important question is, are we using jitsi or zulip?.
r? @rust-lang/types

Type team office hours start in 2025

---

wg-performance.toml

I am disabling this weekly wg-perf triage event because it is superseded by the other events in the same file that also clarify the rotation time (monthly) and who is in charge of the triaging.
Note: Let's not merge this yet since Felix retired from the perf rotation. So maybe it makes sense to use this patch to also update the rotation shifts (either we find another volunteer or re-assign the shifts on the remaining people), see [Zulip thread](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/volunteers.20to.20take.20my.20~4-weekly.20rustc-perf.20slot.3F/near/486629784).
cc @pnkfelix
Thanks

Remove redundant wg-perf triage event

---

compiler.events-only.toml

As per conversation with T-compiler leads, we are scheduling an extra steering meeting to recover the one that slipped on Jan, 31th
cc @wesleywiser @davidtwco

Schedule T-compiler extra steering meeting

---

all.toml
release-team.toml
release.toml

I opted for creating a new calendar for the release team rather than re-purposing release.toml, since I think that makes more sense than asking any users to shift over to the new subscription source.
r? @spastorino

Separate release team calendar and Rust release calendars

---

release.toml

This PR https://github.com/rust-lang/calendar/pull/79 changed a release team event without bumping the last_modified_on attribute.

Bump release last_modified_on

---

compiler.events-only.toml

Unfortunately the meetings in commit 956ffe2 bear the wrong date.
This should fix my mistake and let the meetings appear in calendar clients.

Fix next compiler meetings dates

---

.github/workflows/calendar.yml
.github/workflows/ci.yml
.github/workflows/mr.yml

Ubuntu 20.04 was deprecated a few days ago, see
https://github.com/actions/runner-images/issues/11101
I had a failure on the last patch I merged
https://github.com/rust-lang/calendar/actions/runs/14627688168
r? @Kobzol for an opinion: should be fairly straightforward, right?
Thanks

Upgrade Ubuntu image for CI

---

wg-performance.toml

I reset the rotation starting from May 2025, because it was becoming quite messy to change the rotation to be in sync while keeping the original start dates.

Add panstromek to Performance triage rotation

---

wg-performance.toml

Switched the rotation back to three weeks, and reset it so that it starts from this week.
CC @Mark-Simulacrum

Remove rylev from performance triage rotation
